#!/bin/sh

PROJECT=""
WORKDIR=""

# Manually set the PROJECT and WORKDIR
while [ $# -gt 0 ]; do
  case $1 in
    --project | -p ) PROJECT="${2}"; shift; shift;;
    *) shift;;
  esac
done

# If project is set, it is used to narrow down results. all project bookmarks must start with prj.
MATCH_PROJECTS="$(find "${NNN_BOOKMARKS_DIR:-${HOME}/.cache/nnn/bookmarks}" -maxdepth 1 -type l \
  -name "dev-${PROJECT}*" -printf '%f\n')"
[ -n "${MATCH_PROJECTS}" ] && {
  [ "$(echo -e "${MATCH_PROJECTS}" | wc -l)" -gt 1 ] && {
    [ -n "$(command -v entry-selector)" ] || {
      echo "Entry selector tool not found !"
      exit 1
    }
    PROJECT="$(entry-selector -v "${MATCH_PROJECTS}" -t " projects")"
    [ -z "${PROJECT}" ] && {
      echo "No project selected"
      exit 0
    } || true
  } || {
    PROJECT="${MATCH_PROJECTS}"
  }
  WORKDIR="$(readlink -f ${NNN_BOOKMARKS_DIR:-${HOME}/.cache/nnn/bookmarks}/${PROJECT})"
} || {
  echo "No ${PROJECT}${PROJECT:+ }project found !"
  exit 0
}

[ $(tmux list-sessions | grep -c "${PROJECT}") -gt 0 ] && {
  [ $(pgrep -a alacritty | grep -c "${PROJECT}") -gt 0 ] && {
    exit 0
  } || true
} || {
  tmux new-session -d -c "${WORKDIR}" -s "${PROJECT}" -n "${PROJECT}_nvim"
  tmux selectp -t 1

  # C-m is "Enter". Launch vim then toggle vim-workspace and nerdtree on, along with a term on another window
  tmux send-keys "nvim" C-m
  sleep 1
  tmux send-keys C-t

  tmux new-window -n "${PROJECT}_term"
  tmux selectw -t "${PROJECT}_term"
  tmux selectp -t 1
  tmux send-keys "cd ${WORKDIR}" C-m
  tmux selectw -t "${PROJECT}_nvim"
}

alacritty --class "DevTerm,DevTerm" -t "${PROJECT}" -e tmux attach-session -t "${PROJECT}" &
exit 0;

