#!/bin/sh

[ $(tmux list-sessions | grep -c "mail") -gt 0 ] && {
  [ $(pgrep -a alacritty | grep -c "MailTerm") -gt 0 ] && {
    /opt/local/dwm/bin/dwm-msg run_command view $((1 << 2));
    exit 0;
  } || true;
} || {
  tmux new-session -d -c ~/.local/share/mail -s mail -n mutt
  tmux selectp -t 1

  # C-m is "Enter" -> executes mutt in tmux
  tmux send-keys "pyenv activate mail" C-m
  tmux send-keys "neomutt" C-m
  tmux splitw -h -p 35
  tmux send-keys "khal interactive" C-m
}

alacritty -t "MailTerm" -e tmux attach-session -t mail &
exit 0;

